from aiogram import Router, F
from aiogram.types import Message
from aiogram.filters import Command
from database.db import (
    get_all_users, get_all_vpn_configs, adjust_balance,
    add_vpn_config, toggle_vpn_active, set_admin, set_premium,
    get_user_by_telegram_id, admin_add_upgrade, admin_delete_upgrade,
    delete_vpn_config, get_all_click_upgrades, get_all_user_upgrades,
    get_all_vpn_purchases
)
from config import ADMIN_IDS
from datetime import datetime

router = Router()


async def is_admin(telegram_id: int) -> bool:
    if telegram_id in ADMIN_IDS:
        return True
    user = await get_user_by_telegram_id(telegram_id)
    return bool(user and user.is_admin)


@router.message(Command("admin"))
async def cmd_admin(message: Message):
    if not await is_admin(message.from_user.id):
        await message.answer("❌ Нет доступа.")
        return
    await message.answer(
        "🛠 <b>Админ-панель</b>\n\n"
        "<b>Пользователи:</b>\n"
        "/users — список всех\n"
        "/addbalance [id] [сумма] — пополнить\n"
        "/removebalance [id] [сумма] — снять\n"
        "/setadmin [id] · /removeadmin [id]\n"
        "/setpremium [id] · /removepremium [id]\n\n"
        "<b>VPN:</b>\n"
        "/addvpn — добавить конфиг (пошагово)\n"
        "/vpnlist — все конфиги\n"
        "/togglevpn [id] · /deletevpn [id]\n\n"
        "<b>Улучшения:</b>\n"
        "/addupgrade — добавить улучшение\n"
        "/upgradelist — все улучшения\n"
        "/deleteupgrade [id]\n\n"
        "<b>База данных:</b>\n"
        "/db — полный экспорт БД (ZIP с 5 CSV)",
        parse_mode="HTML"
    )


@router.message(Command("db"))
async def cmd_db(message: Message):
    if not await is_admin(message.from_user.id):
        await message.answer("❌ Нет доступа.")
        return
    import io, csv, zipfile
    from aiogram.types import BufferedInputFile

    users       = await get_all_users()
    upgrades    = await get_all_click_upgrades()
    user_upgs   = await get_all_user_upgrades()
    vpn_cfgs    = await get_all_vpn_configs()
    vpn_purch   = await get_all_vpn_purchases()

    def make_csv(headers, rows):
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(headers)
        for r in rows:
            w.writerow(r)
        return buf.getvalue().encode('utf-8-sig')

    def fmt(dt):
        return dt.strftime('%Y-%m-%d %H:%M:%S') if dt else ''

    users_csv = make_csv(
        ['id','telegram_id','username','first_name','balance','total_clicks',
         'clicks_per_click','auto_clicks_per_second','is_admin','is_premium','premium_until','created_at'],
        [[u.id, u.telegram_id, u.username or '', u.first_name or '',
          round(u.balance,2), u.total_clicks, u.clicks_per_click,
          round(u.auto_clicks_per_second,3), u.is_admin, u.is_premium,
          fmt(u.premium_until), fmt(u.created_at)] for u in users]
    )
    upgrades_csv = make_csv(
        ['id','name','description','price','upgrade_type','clicks_bonus',
         'auto_click_bonus','icon','is_premium_only','is_active','created_at'],
        [[u.id, u.name, u.description or '', round(u.price,2), u.upgrade_type,
          u.clicks_bonus, round(u.auto_click_bonus,3), u.icon,
          u.is_premium_only, u.is_active, fmt(u.created_at)] for u in upgrades]
    )
    user_upgs_csv = make_csv(
        ['id','user_id','upgrade_id','purchased_at'],
        [[u.id, u.user_id, u.upgrade_id, fmt(u.purchased_at)] for u in user_upgs]
    )
    vpn_csv = make_csv(
        ['id','name','description','price_clicks','duration_days','quantity',
         'quantity_left','is_active','available_until','created_at','created_by'],
        [[v.id, v.name, v.description or '', round(v.price_clicks,2),
          v.duration_days, v.quantity, v.quantity_left, v.is_active,
          fmt(v.available_until), fmt(v.created_at), v.created_by or ''] for v in vpn_cfgs]
    )
    vpn_purch_csv = make_csv(
        ['id','user_id','vpn_config_id','price_paid','purchased_at','expires_at'],
        [[p.id, p.user_id, p.vpn_config_id, round(p.price_paid,2),
          fmt(p.purchased_at), fmt(p.expires_at)] for p in vpn_purch]
    )

    def sql_val(v):
        if v is None: return 'NULL'
        if isinstance(v, bool): return 'TRUE' if v else 'FALSE'
        if isinstance(v, (int, float)): return str(v)
        return "'" + str(v).replace("'","''") + "'"

    lines = [
        "-- PostgreSQL dump generated by /db command",
        f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", "",
        "SET client_encoding = 'UTF8';",
        "SET standard_conforming_strings = on;", "",
    ]
    def dump_table(name, cols, rows_data):
        if not rows_data: return
        lines.append(f"-- Table: {name}")
        lines.append(f"DELETE FROM {name};")
        for row in rows_data:
            vals = ', '.join(sql_val(v) for v in row)
            lines.append(f"INSERT INTO {name} ({', '.join(cols)}) VALUES ({vals});")
        lines.append("")

    dump_table('users',
        ['id','telegram_id','username','first_name','balance','total_clicks',
         'clicks_per_click','auto_clicks_per_second','is_admin','is_premium','premium_until','created_at'],
        [[u.id, u.telegram_id, u.username, u.first_name, round(u.balance,2), u.total_clicks,
          u.clicks_per_click, round(u.auto_clicks_per_second,3), u.is_admin, u.is_premium,
          u.premium_until, u.created_at] for u in users])
    dump_table('click_upgrades',
        ['id','name','description','price','upgrade_type','clicks_bonus',
         'auto_click_bonus','icon','is_premium_only','is_active','created_at'],
        [[u.id, u.name, u.description, round(u.price,2), u.upgrade_type,
          u.clicks_bonus, round(u.auto_click_bonus,3), u.icon,
          u.is_premium_only, u.is_active, u.created_at] for u in upgrades])
    dump_table('user_upgrades',
        ['id','user_id','upgrade_id','purchased_at'],
        [[u.id, u.user_id, u.upgrade_id, u.purchased_at] for u in user_upgs])
    dump_table('vpn_configs',
        ['id','name','description','config_data','price_clicks','duration_days',
         'quantity','quantity_left','is_active','available_until','created_at','created_by'],
        [[v.id, v.name, v.description, v.config_data, round(v.price_clicks,2),
          v.duration_days, v.quantity, v.quantity_left, v.is_active,
          v.available_until, v.created_at, v.created_by] for v in vpn_cfgs])
    dump_table('vpn_purchases',
        ['id','user_id','vpn_config_id','price_paid','purchased_at','expires_at'],
        [[p.id, p.user_id, p.vpn_config_id, round(p.price_paid,2),
          p.purchased_at, p.expires_at] for p in vpn_purch])

    lines += [
        "-- Reset sequences",
        "SELECT setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users),1));",
        "SELECT setval('click_upgrades_id_seq', COALESCE((SELECT MAX(id) FROM click_upgrades),1));",
        "SELECT setval('user_upgrades_id_seq', COALESCE((SELECT MAX(id) FROM user_upgrades),1));",
        "SELECT setval('vpn_configs_id_seq', COALESCE((SELECT MAX(id) FROM vpn_configs),1));",
        "SELECT setval('vpn_purchases_id_seq', COALESCE((SELECT MAX(id) FROM vpn_purchases),1));",
    ]
    sql_dump = '\n'.join(lines).encode('utf-8')

    zip_buf = io.BytesIO()
    ts = datetime.now().strftime('%Y%m%d_%H%M%S')
    with zipfile.ZipFile(zip_buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('users.csv',        users_csv)
        zf.writestr('click_upgrades.csv', upgrades_csv)
        zf.writestr('user_upgrades.csv', user_upgs_csv)
        zf.writestr('vpn_configs.csv',  vpn_csv)
        zf.writestr('vpn_purchases.csv', vpn_purch_csv)
        zf.writestr(f'dump_{ts}.sql',   sql_dump)
    zip_buf.seek(0)

    doc = BufferedInputFile(zip_buf.read(), filename=f"database_{ts}.zip")
    await message.answer_document(
        doc,
        caption=(
            f"🗄 <b>Полный экспорт базы данных</b>\n\n"
            f"👥 Пользователей: <b>{len(users)}</b>\n"
            f"⚡ Улучшений: <b>{len(upgrades)}</b>\n"
            f"🛒 Покупок улучшений: <b>{len(user_upgs)}</b>\n"
            f"🔒 VPN конфигов: <b>{len(vpn_cfgs)}</b>\n"
            f"📦 Покупок VPN: <b>{len(vpn_purch)}</b>"
        ),
        parse_mode="HTML"
    )


@router.message(Command("users"))
async def cmd_users(message: Message):
    if not await is_admin(message.from_user.id):
        return
    users = await get_all_users()
    if not users:
        await message.answer("Нет пользователей.")
        return
    lines = ["👥 <b>Пользователи:</b>\n"]
    for u in users[:25]:
        name = u.first_name or u.username or "—"
        marks = ("👑" if u.is_admin else "") + ("⭐" if u.is_premium else "")
        lines.append(f"• <b>{name}</b> {marks}\n  ID:<code>{u.telegram_id}</code> · 💰{int(u.balance)} · 🖱{u.total_clicks}")
    if len(users) > 25:
        lines.append(f"\n…и ещё {len(users)-25}")
    await message.answer("\n".join(lines), parse_mode="HTML")


@router.message(Command("addbalance"))
async def cmd_add_balance(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 3:
        await message.answer("Использование: /addbalance [tg_id] [сумма]")
        return
    try:
        tg_id = int(parts[1]); amount = float(parts[2])
    except ValueError:
        await message.answer("❌ Неверный формат")
        return
    result = await adjust_balance(tg_id, amount)
    if result["ok"]:
        await message.answer(f"✅ Новый баланс: <b>{int(result['new_balance'])}</b>", parse_mode="HTML")
    else:
        await message.answer(f"❌ {result['error']}")


@router.message(Command("removebalance"))
async def cmd_remove_balance(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 3:
        await message.answer("Использование: /removebalance [tg_id] [сумма]")
        return
    try:
        tg_id = int(parts[1]); amount = float(parts[2])
    except ValueError:
        await message.answer("❌ Неверный формат")
        return
    result = await adjust_balance(tg_id, -amount)
    if result["ok"]:
        await message.answer(f"✅ Новый баланс: <b>{int(result['new_balance'])}</b>", parse_mode="HTML")
    else:
        await message.answer(f"❌ {result['error']}")


@router.message(Command("setadmin"))
async def cmd_set_admin(message: Message):
    if message.from_user.id not in ADMIN_IDS:
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /setadmin [tg_id]")
        return
    try:
        tg_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await set_admin(tg_id, True)
    await message.answer(f"✅ Права админа выданы {tg_id}" if result["ok"] else f"❌ {result['error']}")


@router.message(Command("removeadmin"))
async def cmd_remove_admin(message: Message):
    if message.from_user.id not in ADMIN_IDS:
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /removeadmin [tg_id]")
        return
    try:
        tg_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await set_admin(tg_id, False)
    await message.answer(f"✅ Права сняты" if result["ok"] else f"❌ {result['error']}")


@router.message(Command("setpremium"))
async def cmd_set_premium(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /setpremium [tg_id]")
        return
    try:
        tg_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await set_premium(tg_id, True)
    await message.answer(f"✅ Premium выдан {tg_id}" if result["ok"] else f"❌ {result['error']}")


@router.message(Command("removepremium"))
async def cmd_remove_premium(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /removepremium [tg_id]")
        return
    try:
        tg_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await set_premium(tg_id, False)
    await message.answer(f"✅ Premium снят" if result["ok"] else f"❌ {result['error']}")


@router.message(Command("vpnlist"))
async def cmd_vpn_list(message: Message):
    if not await is_admin(message.from_user.id):
        return
    configs = await get_all_vpn_configs()
    if not configs:
        await message.answer("VPN конфигов нет. Добавьте через /addvpn")
        return
    lines = ["📋 <b>VPN конфиги:</b>\n"]
    for c in configs:
        status = "✅" if c.is_active else "❌"
        until = c.available_until.strftime("%d.%m.%Y") if c.available_until else "∞"
        lines.append(f"{status} <b>[{c.id}] {c.name}</b>\n  💰{int(c.price_clicks)} · ⏳{c.duration_days}д. · 📦{c.quantity_left}/{c.quantity} · 📅{until}")
    await message.answer("\n".join(lines), parse_mode="HTML")


@router.message(Command("togglevpn"))
async def cmd_toggle_vpn(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /togglevpn [id]")
        return
    try:
        vpn_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await toggle_vpn_active(vpn_id)
    if result["ok"]:
        await message.answer(f"VPN [{vpn_id}] {'включён ✅' if result['is_active'] else 'отключён ❌'}")
    else:
        await message.answer(f"❌ {result['error']}")


@router.message(Command("deletevpn"))
async def cmd_delete_vpn(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /deletevpn [id]")
        return
    try:
        vpn_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await delete_vpn_config(vpn_id)
    await message.answer("✅ VPN конфиг удалён" if result["ok"] else f"❌ {result['error']}")


@router.message(Command("upgradelist"))
async def cmd_upgrade_list(message: Message):
    if not await is_admin(message.from_user.id):
        return
    from database.db import get_upgrades
    upgrades = await get_upgrades()
    if not upgrades:
        await message.answer("Улучшений нет.")
        return
    lines = ["⚡ <b>Улучшения:</b>\n"]
    for u in upgrades:
        prem = " ⭐" if u.is_premium_only else ""
        bonus = f"+{u.auto_click_bonus}/сек" if u.upgrade_type == "autoclk" else f"+{u.clicks_bonus} клик/тап"
        lines.append(f"• <b>[{u.id}] {u.icon} {u.name}</b>{prem}\n  💰{int(u.price)} · {bonus}")
    await message.answer("\n".join(lines), parse_mode="HTML")


@router.message(Command("deleteupgrade"))
async def cmd_delete_upgrade(message: Message):
    if not await is_admin(message.from_user.id):
        return
    parts = message.text.split()
    if len(parts) != 2:
        await message.answer("Использование: /deleteupgrade [id]")
        return
    try:
        upg_id = int(parts[1])
    except ValueError:
        await message.answer("❌ Неверный ID")
        return
    result = await admin_delete_upgrade(upg_id)
    await message.answer("✅ Улучшение удалено" if result["ok"] else f"❌ {result['error']}")


# ── Пошаговое добавление VPN ──
_vpn_states = {}

@router.message(Command("addvpn"))
async def cmd_add_vpn_start(message: Message):
    if not await is_admin(message.from_user.id):
        return
    _vpn_states[message.from_user.id] = {"step": "name"}
    await message.answer("➕ <b>Добавление VPN</b>\n\nШаг 1/6: <b>Название</b>:", parse_mode="HTML")


# ── Пошаговое добавление Upgrade ──
_upg_states = {}

@router.message(Command("addupgrade"))
async def cmd_add_upgrade_start(message: Message):
    if not await is_admin(message.from_user.id):
        return
    _upg_states[message.from_user.id] = {"step": "name"}
    await message.answer(
        "➕ <b>Добавление улучшения</b>\n\nШаг 1/6: <b>Название</b>:",
        parse_mode="HTML"
    )


@router.message(F.text)
async def handle_steps(message: Message):
    uid = message.from_user.id

    if uid in _vpn_states:
        state = _vpn_states[uid]
        step = state.get("step")
        if step == "name":
            state["name"] = message.text; state["step"] = "description"
            await message.answer("Шаг 2/6: <b>Описание</b>:", parse_mode="HTML")
        elif step == "description":
            state["description"] = message.text; state["step"] = "config_data"
            await message.answer("Шаг 3/6: <b>Конфиг VPN</b> (текст/ключ):", parse_mode="HTML")
        elif step == "config_data":
            state["config_data"] = message.text; state["step"] = "price"
            await message.answer("Шаг 4/6: <b>Цена в кликах</b>:", parse_mode="HTML")
        elif step == "price":
            try: state["price_clicks"] = float(message.text)
            except ValueError: await message.answer("❌ Введите число!"); return
            state["step"] = "duration"
            await message.answer("Шаг 5/6: <b>Срок действия (дней)</b>:", parse_mode="HTML")
        elif step == "duration":
            try: state["duration_days"] = int(message.text)
            except ValueError: await message.answer("❌ Введите целое число!"); return
            state["step"] = "quantity"
            await message.answer("Шаг 6/6: <b>Количество в наличии</b>:", parse_mode="HTML")
        elif step == "quantity":
            try: state["quantity"] = int(message.text)
            except ValueError: await message.answer("❌ Введите целое число!"); return
            state["step"] = "available_until"
            await message.answer("Последний шаг: <b>Дата окончания</b> (ДД.ММ.ГГГГ или <code>нет</code>):", parse_mode="HTML")
        elif step == "available_until":
            available_until = None
            if message.text.lower() not in ("нет", "no", "-"):
                try: available_until = datetime.strptime(message.text.strip(), "%d.%m.%Y")
                except ValueError: await message.answer("❌ Формат: ДД.ММ.ГГГГ или 'нет'"); return
            vpn = await add_vpn_config(
                name=state["name"], description=state["description"],
                config_data=state["config_data"], price_clicks=state["price_clicks"],
                duration_days=state["duration_days"], quantity=state["quantity"],
                available_until=available_until, created_by=uid
            )
            del _vpn_states[uid]
            await message.answer(f"✅ <b>VPN добавлен!</b> ID: {vpn.id}\n{vpn.name} · 💰{int(vpn.price_clicks)} · ⏳{vpn.duration_days}д.", parse_mode="HTML")
        return

    if uid in _upg_states:
        state = _upg_states[uid]
        step = state.get("step")
        if step == "name":
            state["name"] = message.text; state["step"] = "description"
            await message.answer("Шаг 2/6: <b>Описание</b>:", parse_mode="HTML")
        elif step == "description":
            state["description"] = message.text; state["step"] = "icon"
            await message.answer("Шаг 3/6: <b>Иконка</b> (эмодзи, напр. ⚡):", parse_mode="HTML")
        elif step == "icon":
            state["icon"] = message.text.strip() or "⚡"; state["step"] = "price"
            await message.answer("Шаг 4/6: <b>Цена в кликах</b>:", parse_mode="HTML")
        elif step == "price":
            try: state["price"] = float(message.text)
            except ValueError: await message.answer("❌ Введите число!"); return
            state["step"] = "type"
            await message.answer("Шаг 5/6: <b>Тип</b> — напишите:\n<code>click</code> — +клики за тап\n<code>auto</code> — авто-клик/сек", parse_mode="HTML")
        elif step == "type":
            t = message.text.strip().lower()
            if t not in ("click", "auto", "autoclk"):
                await message.answer("❌ Введите <code>click</code> или <code>auto</code>", parse_mode="HTML"); return
            state["type"] = "autoclk" if t == "auto" else "click"
            state["step"] = "bonus"
            lbl = "авто-кликов в секунду (напр. 1.5)" if state["type"] == "autoclk" else "бонус кликов за тап (напр. 5)"
            await message.answer(f"Шаг 6/6: <b>Укажите {lbl}</b>:", parse_mode="HTML")
        elif step == "bonus":
            try: bonus = float(message.text)
            except ValueError: await message.answer("❌ Введите число!"); return
            state["step"] = "premium"
            state["bonus"] = bonus
            await message.answer("Последний шаг: <b>Только для Premium?</b> (да / нет):", parse_mode="HTML")
        elif step == "premium":
            is_prem = message.text.strip().lower() in ("да", "yes", "y", "+")
            clicks_bonus = 0 if state["type"] == "autoclk" else int(state["bonus"])
            auto_bonus   = state["bonus"] if state["type"] == "autoclk" else 0.0
            upg = await admin_add_upgrade(
                name=state["name"], description=state["description"],
                price=state["price"], upgrade_type=state["type"],
                clicks_bonus=clicks_bonus, auto_click_bonus=auto_bonus,
                icon=state["icon"], is_premium_only=is_prem
            )
            del _upg_states[uid]
            prem_mark = " ⭐ Premium only" if is_prem else ""
            await message.answer(f"✅ <b>Улучшение добавлено!</b> ID: {upg.id}\n{upg.icon} {upg.name} · 💰{int(upg.price)}{prem_mark}", parse_mode="HTML")
        return
